# Generated by Django 4.2.3 on 2023-10-02 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="pdfdatasource", name="chatbot_id",),
        migrations.AddField(
            model_name="crawledpages",
            name="content_file",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="pdfdatasource",
            name="chatbot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdf_data_sources",
                to="web.chatbot",
            ),
        ),
        migrations.AlterField(
            model_name="crawledpages",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
